services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    ports:
      - "8443:8443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - PASSWORD=123456
      # - HASHED_PASSWORD=  # PASSWORD yerine ileri seviye istersen
    volumes:
      - code_server_config:/config

volumes:
  code_server_config:
